#!/usr/bin/env python
# coding: utf-8

# ==============================================================
#                         IMPORTS
# ==============================================================
import logging
from contextlib import contextmanager
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.orm.exc import NoResultFound
from payment_gateway.transaction_format import TransactionFormat
from payment_gateway.database import CardInformation, PaymentStatus

# ==============================================================
#                          BASE
# ==============================================================


class RetrievePayment:
    """ Class to retrieve payment details
    """
    def __init__(self, db_uri='sqlite:///./test.db'):
        self.engine = create_engine(db_uri, echo=True)
        CardInformation.metadata.create_all(self.engine)
        PaymentStatus.metadata.create_all(self.engine)
        self.Session = sessionmaker(bind=self.engine)
        self.logger = logging.getLogger(__name__)
    
    def get_payment(self, payment_identifier: int) -> dict:
        """ Return Payment details according to the id provided
            by the merchant.
        """
        